version: '3.9'

services:
  front:
    container_name: reportituf-front
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - "3456:3000"
      - "24680:24678"
    volumes:
      - .:/app
      - front_node_modules:/app/node_modules
      - front_nuxt:/app/.nuxt
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - NUXT_PUBLIC_API_BASE=http://localhost:8000/api
      - NITRO_HOST=0.0.0.0
      - NITRO_PORT=3000
    stdin_open: true
    tty: true

volumes:
  front_node_modules:
    driver: local
  front_nuxt:
    driver: local